apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: site-example-hpa
  namespace: site-example-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: site-example
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
